// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_jXNvEHTWQZk8iTV4xLqsPJGugBy56UI',
    appId: '1:344357181016:web:94e3b169311acd07199c2d',
    messagingSenderId: '344357181016',
    projectId: 'myteethiraq-7930a',
    authDomain: 'myteethiraq-7930a.firebaseapp.com',
    storageBucket: 'myteethiraq-7930a.appspot.com',
    measurementId: 'G-XWHMR6T7YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMil19qc-ONuJZECmByp5GD1s-FKisnBM',
    appId: '1:344357181016:android:00e7d8ed71b76199199c2d',
    messagingSenderId: '344357181016',
    projectId: 'myteethiraq-7930a',
    storageBucket: 'myteethiraq-7930a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAda_MgPZ9uNg4VwgR9w1AvbnPxhJ7wR6o',
    appId: '1:344357181016:ios:880065b54b5f8e0a199c2d',
    messagingSenderId: '344357181016',
    projectId: 'myteethiraq-7930a',
    storageBucket: 'myteethiraq-7930a.appspot.com',
    iosClientId: '344357181016-viap842r8q75htt6boa7qe2ma7l80gtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTeethApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAda_MgPZ9uNg4VwgR9w1AvbnPxhJ7wR6o',
    appId: '1:344357181016:ios:880065b54b5f8e0a199c2d',
    messagingSenderId: '344357181016',
    projectId: 'myteethiraq-7930a',
    storageBucket: 'myteethiraq-7930a.appspot.com',
    iosClientId: '344357181016-viap842r8q75htt6boa7qe2ma7l80gtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTeethApp',
  );
}
